### PR TITLE
refactor: rename "obs" -> "obsidian-cli"

### PR DESCRIPTION
**Pull request by danielwerg**
- [x] Create new gifs (https://github.com/Yakitrak/obs/blob/main/assets/images/terminal-create-note.gif, https://github.com/Yakitrak/obs/blob/main/assets/images/terminal-move-note.gif)
- [x] Rename brew package (https://github.com/Yakitrak/obs/blob/main/index.md?plain=1#L16, https://github.com/Yakitrak/obs/blob/main/docs/install/mac-and-linux.md?plain=1#L27, https://github.com/Yakitrak/obs/blob/main/docs/install/mac-and-linux.md?plain=1#L30)
- [x] Rename scoop package (https://github.com/Yakitrak/obs/blob/main/docs/install/windows.md?plain=1#L24)
- [ ] Rename this repo to "obsidian-cli-website" to match "obsidian-cli" repo name

Related: https://github.com/Yakitrak/obsidian-cli/pull/31#issuecomment-2212418185

### CODE REVIEW

**Comment by danielwerg** [comment]
@Yakitrak Couple things.

1. What did you used to create gifs?
2. Let me know when it is safe to rename brew and scoop package name in docs

**Comment by danielwerg** [comment]
We can also add [aur package](https://aur.archlinux.org/packages/obs-bin) maintained by @jneidel to docs install page! 

@jneidel `obs-bin` will have to be renamed to `obsd-bin` once https://github.com/Yakitrak/obsidian-cli/pull/31 is merged.

**Comment by danielwerg** [comment]
@jneidel I wasn't a part of discussion until https://github.com/Yakitrak/obsidian-cli/pull/31#issuecomment-2220943864, so maybe wait for @Yakitrak final decision.

**Comment by Yakitrak** [comment]
> @Yakitrak Couple things.
> 
>     1. What did you used to create gifs?
> 
>     2. Let me know when it is safe to rename brew and scoop package name in docs


Thanks for making a PR here as well, appreciate your work on this.

1. I use this for the terminal gifs: https://www.terminalgif.com/
2. It should be okay once we decide and merge on the obsidian-cli repo including the goreleaser changes.

Both of those repos are public as well and should auto generate:
- https://github.com/Yakitrak/homebrew-yakitrak
- https://github.com/Yakitrak/scoop-yakitrak

**Comment by danielwerg** [comment]
terminal-1
[terminal-commands-1.json](https://github.com/user-attachments/files/16168460/terminal-commands-1.json)

terminal-2
[terminal-commands-2.json](https://github.com/user-attachments/files/16168458/terminal-commands-2.json)

**Comment by danielwerg** [comment]
https://github.com/Yakitrak/homebrew-yakitrak/pull/1
https://github.com/Yakitrak/scoop-yakitrak/pull/1

**Comment by danielwerg** [comment]
@jneidel
> Sure, if you have decided on obsd-bin then I can take the preparations on my end.

We decided on `obsdian-cli`! Thank you for maintaining AUR package!

**Comment by Yakitrak** [comment]
> [Yakitrak/homebrew-yakitrak#1](https://github.com/Yakitrak/homebrew-yakitrak/pull/1) [Yakitrak/scoop-yakitrak#1](https://github.com/Yakitrak/scoop-yakitrak/pull/1)

This should be autogenerated once goreleaser runs if I remember correctly.

**Comment by danielwerg** [comment]
> This should be autogenerated once goreleaser runs if I remember correctly.

Ooops, couldn't read last nights :D

**Review by danielwerg — COMMENTED** [review]
self-review

**Comment by jneidel** [comment]
[AUR package](https://aur.archlinux.org/packages/obsidian-cli) is ready for the namechange to `obsidian-cli` :+1:

**Comment by jneidel** [comment]
MR for relevant goreleaser changes: https://github.com/Yakitrak/obsidian-cli/pull/32

**Review by Yakitrak — APPROVED** [review]
LGTM - thank you

**Pull request merged**
